"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Field_1 = require("./Field");
const FieldType_1 = require("./FieldType");
const FieldConnection_1 = require("./FieldConnection");
const Collections = require("typescript-collections");
class Map {
    constructor() {
        this.fields = new Collections.Dictionary();
        this.black = new Field_1.Field('black', FieldType_1.FieldType.HOMEBASE);
        this.blue = new Field_1.Field('blue', FieldType_1.FieldType.HOMEBASE);
        this.green = new Field_1.Field('green', FieldType_1.FieldType.HOMEBASE);
        this.purple = new Field_1.Field('purple', FieldType_1.FieldType.HOMEBASE);
        this.red = new Field_1.Field('red', FieldType_1.FieldType.HOMEBASE);
        this.white = new Field_1.Field('white', FieldType_1.FieldType.HOMEBASE);
        this.yellow = new Field_1.Field('yellow', FieldType_1.FieldType.HOMEBASE);
        this.F = new Field_1.Field('F', FieldType_1.FieldType.FACTORY);
        this.f1 = new Field_1.Field('f1', FieldType_1.FieldType.FARM);
        this.f2 = new Field_1.Field('f2', FieldType_1.FieldType.FARM);
        this.f3 = new Field_1.Field('f3', FieldType_1.FieldType.FARM);
        this.f4 = new Field_1.Field('f4', FieldType_1.FieldType.FARM);
        this.f5 = new Field_1.Field('f5', FieldType_1.FieldType.FARM);
        this.f6 = new Field_1.Field('f6', FieldType_1.FieldType.FARM);
        this.f7 = new Field_1.Field('f7', FieldType_1.FieldType.FARM);
        this.l1 = new Field_1.Field('l1', FieldType_1.FieldType.LAKE);
        this.l2 = new Field_1.Field('l2', FieldType_1.FieldType.LAKE);
        this.l4 = new Field_1.Field('l4', FieldType_1.FieldType.LAKE);
        this.l5 = new Field_1.Field('l5', FieldType_1.FieldType.LAKE);
        this.l6 = new Field_1.Field('l6', FieldType_1.FieldType.LAKE);
        this.l7 = new Field_1.Field('l7', FieldType_1.FieldType.LAKE);
        this.m1 = new Field_1.Field('m1', FieldType_1.FieldType.MOUNTAIN);
        this.m2 = new Field_1.Field('m2', FieldType_1.FieldType.MOUNTAIN);
        this.m3 = new Field_1.Field('m3', FieldType_1.FieldType.MOUNTAIN);
        this.m4 = new Field_1.Field('m4', FieldType_1.FieldType.MOUNTAIN);
        this.m5 = new Field_1.Field('m5', FieldType_1.FieldType.MOUNTAIN);
        this.m6 = new Field_1.Field('m6', FieldType_1.FieldType.MOUNTAIN);
        this.m7 = new Field_1.Field('m7', FieldType_1.FieldType.MOUNTAIN);
        this.m8 = new Field_1.Field('m8', FieldType_1.FieldType.MOUNTAIN);
        this.t1 = new Field_1.Field('t1', FieldType_1.FieldType.TUNDRA);
        this.t2 = new Field_1.Field('t2', FieldType_1.FieldType.TUNDRA);
        this.t3 = new Field_1.Field('t3', FieldType_1.FieldType.TUNDRA);
        this.t4 = new Field_1.Field('t4', FieldType_1.FieldType.TUNDRA);
        this.t5 = new Field_1.Field('t5', FieldType_1.FieldType.TUNDRA);
        this.t6 = new Field_1.Field('t6', FieldType_1.FieldType.TUNDRA);
        this.t7 = new Field_1.Field('t7', FieldType_1.FieldType.TUNDRA);
        this.t8 = new Field_1.Field('t8', FieldType_1.FieldType.TUNDRA);
        this.v1 = new Field_1.Field('v1', FieldType_1.FieldType.VILLAGE);
        this.v2 = new Field_1.Field('v2', FieldType_1.FieldType.VILLAGE);
        this.v3 = new Field_1.Field('v3', FieldType_1.FieldType.VILLAGE);
        this.v4 = new Field_1.Field('v4', FieldType_1.FieldType.VILLAGE);
        this.v5 = new Field_1.Field('v5', FieldType_1.FieldType.VILLAGE);
        this.v6 = new Field_1.Field('v6', FieldType_1.FieldType.VILLAGE);
        this.v7 = new Field_1.Field('v7', FieldType_1.FieldType.VILLAGE);
        this.v8 = new Field_1.Field('v8', FieldType_1.FieldType.VILLAGE);
        this.v9 = new Field_1.Field('v9', FieldType_1.FieldType.VILLAGE);
        this.w1 = new Field_1.Field('w1', FieldType_1.FieldType.FOREST);
        this.w2 = new Field_1.Field('w2', FieldType_1.FieldType.FOREST);
        this.w3 = new Field_1.Field('w3', FieldType_1.FieldType.FOREST);
        this.w4 = new Field_1.Field('w4', FieldType_1.FieldType.FOREST);
        this.w5 = new Field_1.Field('w5', FieldType_1.FieldType.FOREST);
        this.w6 = new Field_1.Field('w6', FieldType_1.FieldType.FOREST);
        this.w7 = new Field_1.Field('w7', FieldType_1.FieldType.FOREST);
        this.fields.setValue(this.green, [
            { field: this.m1, connectionType: FieldConnection_1.FieldConnection.DEFAULT },
            { field: this.f1, connectionType: FieldConnection_1.FieldConnection.DEFAULT }
        ]);
        this.fields.setValue(this.blue, [
            { field: this.w1, connectionType: FieldConnection_1.FieldConnection.DEFAULT },
            { field: this.t1, connectionType: FieldConnection_1.FieldConnection.DEFAULT }
        ]);
        this.fields.setValue(this.white, [
            { field: this.w2, connectionType: FieldConnection_1.FieldConnection.DEFAULT },
            { field: this.w4, connectionType: FieldConnection_1.FieldConnection.DEFAULT },
            { field: this.l1, connectionType: FieldConnection_1.FieldConnection.DEFAULT }
        ]);
        this.fields.setValue(this.red, [
            { field: this.f3, connectionType: FieldConnection_1.FieldConnection.DEFAULT },
            { field: this.v3, connectionType: FieldConnection_1.FieldConnection.DEFAULT },
            { field: this.m5, connectionType: FieldConnection_1.FieldConnection.DEFAULT }
        ]);
        this.fields.setValue(this.black, [
            { field: this.m6, connectionType: FieldConnection_1.FieldConnection.DEFAULT },
            { field: this.t8, connectionType: FieldConnection_1.FieldConnection.DEFAULT }
        ]);
        this.fields.setValue(this.purple, { field: this.t7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.purple, { field: this.f7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.yellow, { field: this.f6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.yellow, { field: this.v9, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.m1, { field: this.f1, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.m1, { field: this.l1, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.m1, { field: this.t2, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.f1, { field: this.m1, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.f1, { field: this.t2, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.f1, { field: this.l2, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.f1, { field: this.v1, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v1, { field: this.f1, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v1, { field: this.l2, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v1, { field: this.t3, connectionType: FieldConnection_1.FieldConnection.RIVER });
        this.fields.setValue(this.v1, { field: this.w1, connectionType: FieldConnection_1.FieldConnection.RIVER });
        this.fields.setValue(this.w1, { field: this.v1, connectionType: FieldConnection_1.FieldConnection.RIVER });
        this.fields.setValue(this.w1, { field: this.t3, connectionType: FieldConnection_1.FieldConnection.RIVER });
        this.fields.setValue(this.w1, { field: this.m2, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.w1, { field: this.t1, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t1, { field: this.w1, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t1, { field: this.m2, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t1, { field: this.f2, connectionType: FieldConnection_1.FieldConnection.RIVER });
        this.fields.setValue(this.t1, { field: this.v2, connectionType: FieldConnection_1.FieldConnection.RIVER });
        this.fields.setValue(this.v2, { field: this.t1, connectionType: FieldConnection_1.FieldConnection.RIVER });
        this.fields.setValue(this.v2, { field: this.f2, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v2, { field: this.f3, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l1, { field: this.w2, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l1, { field: this.t2, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l1, { field: this.m1, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t2, { field: this.m1, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t2, { field: this.l1, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t2, { field: this.w2, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t2, { field: this.m3, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t2, { field: this.l2, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t2, { field: this.f1, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l2, { field: this.f1, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l2, { field: this.t2, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l2, { field: this.m3, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l2, { field: this.w3, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l2, { field: this.t3, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l2, { field: this.v1, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t3, { field: this.v1, connectionType: FieldConnection_1.FieldConnection.RIVER });
        this.fields.setValue(this.t3, { field: this.l2, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t3, { field: this.w3, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t3, { field: this.l4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t3, { field: this.m2, connectionType: FieldConnection_1.FieldConnection.RIVER });
        this.fields.setValue(this.t3, { field: this.w1, connectionType: FieldConnection_1.FieldConnection.RIVER });
        this.fields.setValue(this.m2, { field: this.w1, connectionType: FieldConnection_1.FieldConnection.RIVER });
        this.fields.setValue(this.m2, { field: this.t3, connectionType: FieldConnection_1.FieldConnection.RIVER });
        this.fields.setValue(this.m2, { field: this.l4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.m2, { field: this.w4, connectionType: FieldConnection_1.FieldConnection.RIVER });
        this.fields.setValue(this.m2, { field: this.f2, connectionType: FieldConnection_1.FieldConnection.RIVER });
        this.fields.setValue(this.m2, { field: this.t1, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.f2, { field: this.t1, connectionType: FieldConnection_1.FieldConnection.RIVER });
        this.fields.setValue(this.f2, { field: this.m2, connectionType: FieldConnection_1.FieldConnection.RIVER });
        this.fields.setValue(this.f2, { field: this.w4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.f2, { field: this.v3, connectionType: FieldConnection_1.FieldConnection.RIVER });
        this.fields.setValue(this.f2, { field: this.f3, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.f2, { field: this.v2, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.f3, { field: this.v2, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.f3, { field: this.f2, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.f3, { field: this.v3, connectionType: FieldConnection_1.FieldConnection.RIVER });
        this.fields.setValue(this.w2, { field: this.l1, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.w2, { field: this.f4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.w2, { field: this.v4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.w2, { field: this.m3, connectionType: FieldConnection_1.FieldConnection.RIVER });
        this.fields.setValue(this.w2, { field: this.t2, connectionType: FieldConnection_1.FieldConnection.RIVER });
        this.fields.setValue(this.m3, { field: this.t2, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.m3, { field: this.w2, connectionType: FieldConnection_1.FieldConnection.RIVER });
        this.fields.setValue(this.m3, { field: this.v4, connectionType: FieldConnection_1.FieldConnection.RIVER });
        this.fields.setValue(this.m3, { field: this.l5, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.m3, { field: this.w3, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.m3, { field: this.l2, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.w3, { field: this.l2, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.w3, { field: this.m3, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.w3, { field: this.l5, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.w3, { field: this.F, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.w3, { field: this.l4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.w3, { field: this.t3, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l4, { field: this.t3, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l4, { field: this.w3, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l4, { field: this.F, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l4, { field: this.m4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l4, { field: this.w4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l4, { field: this.m2, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.w4, { field: this.m2, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.w4, { field: this.l4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.w4, { field: this.m4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.w4, { field: this.t4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.w4, { field: this.v3, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.w4, { field: this.f2, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v3, { field: this.f2, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v3, { field: this.w4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v3, { field: this.t4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v3, { field: this.m5, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v3, { field: this.f3, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.f4, { field: this.w5, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.f4, { field: this.w6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.f4, { field: this.v4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.f4, { field: this.w2, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v4, { field: this.w2, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v4, { field: this.f4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v4, { field: this.w6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v4, { field: this.f5, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v4, { field: this.l5, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v4, { field: this.m3, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l5, { field: this.m3, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l5, { field: this.v4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l5, { field: this.f5, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l5, { field: this.t5, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l5, { field: this.F, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l5, { field: this.w3, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.F, { field: this.w3, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.F, { field: this.l5, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.F, { field: this.t5, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.F, { field: this.l6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.F, { field: this.m4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.F, { field: this.l4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.m4, { field: this.l4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.m4, { field: this.F, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.m4, { field: this.l6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.m4, { field: this.v5, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.m4, { field: this.t4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.m4, { field: this.w4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t4, { field: this.w4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t4, { field: this.m4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t4, { field: this.v5, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t4, { field: this.l7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t4, { field: this.m5, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t4, { field: this.v3, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.m5, { field: this.v3, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.m5, { field: this.t4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.m5, { field: this.l7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.w5, { field: this.m6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.w5, { field: this.w6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.w5, { field: this.f4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.w6, { field: this.f4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.w6, { field: this.w5, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.w6, { field: this.m6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.w6, { field: this.v6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.w6, { field: this.f5, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.w6, { field: this.v4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.f5, { field: this.v4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.f5, { field: this.w6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.f5, { field: this.v6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.f5, { field: this.v7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.f5, { field: this.t5, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.f5, { field: this.l5, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t5, { field: this.l5, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t5, { field: this.f5, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t5, { field: this.v7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t5, { field: this.t6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t5, { field: this.l6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t5, { field: this.F, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l6, { field: this.F, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l6, { field: this.t5, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l6, { field: this.t6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l6, { field: this.w7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l6, { field: this.v5, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l6, { field: this.m4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v5, { field: this.m4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v5, { field: this.l6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v5, { field: this.w7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v5, { field: this.m7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v5, { field: this.l7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v5, { field: this.t4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l7, { field: this.t4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l7, { field: this.v5, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l7, { field: this.m7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l7, { field: this.l7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l7, { field: this.t4, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.m6, { field: this.w5, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.m6, { field: this.t8, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.m6, { field: this.v6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.m6, { field: this.w6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v6, { field: this.w6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v6, { field: this.m6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v6, { field: this.t8, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v6, { field: this.l7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v6, { field: this.v7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v6, { field: this.f5, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v7, { field: this.f5, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v7, { field: this.v6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v7, { field: this.l7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v7, { field: this.f6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v7, { field: this.t6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v7, { field: this.t5, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t6, { field: this.t5, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t6, { field: this.v7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t6, { field: this.f6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t6, { field: this.m8, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t6, { field: this.w7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t6, { field: this.l6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.w7, { field: this.l6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.w7, { field: this.t6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.w7, { field: this.m8, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.w7, { field: this.v8, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.w7, { field: this.m7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.w7, { field: this.v5, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.m7, { field: this.v5, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.m7, { field: this.w7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.m7, { field: this.v8, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.m7, { field: this.f7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.m7, { field: this.t7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.m7, { field: this.l7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t7, { field: this.l7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t7, { field: this.m7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t7, { field: this.f7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t8, { field: this.m6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t8, { field: this.l7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t8, { field: this.v6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l7, { field: this.v6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l7, { field: this.t8, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l7, { field: this.f6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.l7, { field: this.v7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.f6, { field: this.v7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.f6, { field: this.l7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.f6, { field: this.v9, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.f6, { field: this.m8, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.f6, { field: this.t6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.m8, { field: this.t6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.m8, { field: this.f6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.m8, { field: this.v9, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.m8, { field: this.v8, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.m8, { field: this.w7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v8, { field: this.w7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v8, { field: this.m8, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v8, { field: this.f7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v8, { field: this.m7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.f7, { field: this.m7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.f7, { field: this.v8, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.f7, { field: this.t7, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v9, { field: this.f6, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.v9, { field: this.m8, connectionType: FieldConnection_1.FieldConnection.DEFAULT });
        this.fields.setValue(this.t3, { field: this.w4, connectionType: FieldConnection_1.FieldConnection.TUNNEL });
        this.fields.setValue(this.t3, { field: this.m3, connectionType: FieldConnection_1.FieldConnection.TUNNEL });
        this.fields.setValue(this.t3, { field: this.f5, connectionType: FieldConnection_1.FieldConnection.TUNNEL });
        this.fields.setValue(this.t3, { field: this.v5, connectionType: FieldConnection_1.FieldConnection.TUNNEL });
        this.fields.setValue(this.t3, { field: this.t6, connectionType: FieldConnection_1.FieldConnection.TUNNEL });
        this.fields.setValue(this.m3, { field: this.w4, connectionType: FieldConnection_1.FieldConnection.TUNNEL });
        this.fields.setValue(this.m3, { field: this.t3, connectionType: FieldConnection_1.FieldConnection.TUNNEL });
        this.fields.setValue(this.m3, { field: this.f5, connectionType: FieldConnection_1.FieldConnection.TUNNEL });
        this.fields.setValue(this.m3, { field: this.v5, connectionType: FieldConnection_1.FieldConnection.TUNNEL });
        this.fields.setValue(this.m3, { field: this.t6, connectionType: FieldConnection_1.FieldConnection.TUNNEL });
        this.fields.setValue(this.w4, { field: this.t3, connectionType: FieldConnection_1.FieldConnection.TUNNEL });
        this.fields.setValue(this.w4, { field: this.m3, connectionType: FieldConnection_1.FieldConnection.TUNNEL });
        this.fields.setValue(this.w4, { field: this.f5, connectionType: FieldConnection_1.FieldConnection.TUNNEL });
        this.fields.setValue(this.w4, { field: this.v5, connectionType: FieldConnection_1.FieldConnection.TUNNEL });
        this.fields.setValue(this.w4, { field: this.t6, connectionType: FieldConnection_1.FieldConnection.TUNNEL });
        this.fields.setValue(this.f5, { field: this.t3, connectionType: FieldConnection_1.FieldConnection.TUNNEL });
        this.fields.setValue(this.f5, { field: this.m3, connectionType: FieldConnection_1.FieldConnection.TUNNEL });
        this.fields.setValue(this.f5, { field: this.w4, connectionType: FieldConnection_1.FieldConnection.TUNNEL });
        this.fields.setValue(this.f5, { field: this.v5, connectionType: FieldConnection_1.FieldConnection.TUNNEL });
        this.fields.setValue(this.f5, { field: this.t6, connectionType: FieldConnection_1.FieldConnection.TUNNEL });
        this.fields.setValue(this.v5, { field: this.t3, connectionType: FieldConnection_1.FieldConnection.TUNNEL });
        this.fields.setValue(this.v5, { field: this.m3, connectionType: FieldConnection_1.FieldConnection.TUNNEL });
        this.fields.setValue(this.v5, { field: this.w4, connectionType: FieldConnection_1.FieldConnection.TUNNEL });
        this.fields.setValue(this.v5, { field: this.f5, connectionType: FieldConnection_1.FieldConnection.TUNNEL });
        this.fields.setValue(this.v5, { field: this.t6, connectionType: FieldConnection_1.FieldConnection.TUNNEL });
        this.fields.setValue(this.t6, { field: this.t3, connectionType: FieldConnection_1.FieldConnection.TUNNEL });
        this.fields.setValue(this.t6, { field: this.m3, connectionType: FieldConnection_1.FieldConnection.TUNNEL });
        this.fields.setValue(this.t6, { field: this.w4, connectionType: FieldConnection_1.FieldConnection.TUNNEL });
        this.fields.setValue(this.t6, { field: this.f5, connectionType: FieldConnection_1.FieldConnection.TUNNEL });
        this.fields.setValue(this.t6, { field: this.v5, connectionType: FieldConnection_1.FieldConnection.TUNNEL });
    }
    options(name) {
        if (!this.fields.containsKey(name)) {
            return [];
        }
        return this.fields.getValue(name).getConnectedFields()
            .filter((connection) => connection.connection === FieldConnection_1.FieldConnection.DEFAULT)
            .map((connection) => connection.field);
    }
}
exports.Map = Map;
