export enum Star {
    ALL_UPGRADE,
    ALL_MECHS,
    ALL_BUILDINGS,
    ALL_RECRUITS,
    ALL_WORKERS,
    FIRST_OBJECTIVE,
    FIRST_COMBAT_WIN,
    SECOND_COMBAT_WIN,
    MAX_POPULARITY,
    MAX_POWER,
}
