export enum Star {
    ALL_UPGRADES = "ALL_UPGRADES",
    ALL_MECHS = "ALL_MECHS",
    ALL_BUILDINGS = "ALL_BUILDINGS",
    ALL_RECRUITS = "ALL_RECRUITS",
    ALL_WORKERS = "ALL_WORKERS",
    FIRST_OBJECTIVE = "FIRST_OBJECTIVE",
    FIRST_COMBAT_WIN = "FIRST_COMBAT_WIN",
    SECOND_COMBAT_WIN = "SECOND_COMBAT_WIN",
    MAX_POPULARITY = "MAX_POPULARITY",
    MAX_POWER = "MAX_POWER",
}
